### ISSUE TITLE
Can't run application

### ISSUE THREAD

**Issue by alexander-myltsev** [mariussoutier/play-angular-require-seed#37]
Environment: Linux 3.19.0-39-generic #44-Ubuntu SMP Tue Dec 1 14:39:05 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux in Vagrant.

Why is this happening? 

```
$ sbt
sbt> run
...
play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[FileNotFoundException: /play-angular-require-seed/project/target/node-modules/webjars/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/is-property.js (Operation not permitted)]
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:51) ~[na:na]
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
        at scala.Option.map(Option.scala:145) ~[scala-library-2.11.7.jar:na]
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
        at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
        at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
        at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.7.jar:na]
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:17) ~[na:na]
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61) ~[na:na]
Caused by: java.io.FileNotFoundException: /play-angular-require-seed/project/target/node-modules/webjars/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/is-property.js (Operation not permitted)
        at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_66]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_66]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_66]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_66]
        at org.webjars.WebJarExtractor.copyAndClose(WebJarExtractor.java:435) ~[na:na]
        at org.webjars.WebJarExtractor.copyZipEntry(WebJarExtractor.java:301) ~[na:na]
        at org.webjars.WebJarExtractor.extractWebJarsTo(WebJarExtractor.java:131) ~[na:na]
        at org.webjars.WebJarExtractor.extractAllNodeModulesTo(WebJarExtractor.java:81) ~[na:na]
        at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$generateNodeWebJars$1.apply(SbtWeb.scala:388) ~[na:na]
        at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$generateNodeWebJars$1.apply(SbtWeb.scala:387) ~[na:na]
```

**Comment by mariussoutier** [comment]
I don't know.
